branch: master
tagFormat: '${version}'

prepare:
- '@semantic-release/changelog'
- '@alorel-personal/semantic-release'
- &npm '@semantic-release/npm'
- path: &exec '@semantic-release/exec'
  cmd: yarn run doctoc
- path: *exec
  cmd: alo copy-files
- path: *exec
  cmd: alo clean-dist
- path: *exec
  cmd: alo clean-pkg-json
- path: '@semantic-release/git'
  message: 'chore(release): ${nextRelease.version}'
  assets:
  - CHANGELOG.md
  - README.md
  - package.json
  - yarn.lock

publish:
  - path: *npm
    pkgRoot: './dist'
  - '@semantic-release/github'

generateNotes:
  config: '@alorel-personal/conventional-changelog-alorel'
