language: node_js
node_js: lts/*
sudo: false

env:
  global:
  - TS_NODE_CACHE_DIRECTORY=/dev/null

before_install:
- npm i -g greenkeeper-lockfile
- greenkeeper-lockfile-update

install: npm install

after_script: if [[ $GH_TOKEN ]]; then greenkeeper-lockfile-upload; fi;
after_success: cat ./coverage/lcov.info | coveralls

before_cache: rm -rf ./node_modules/.cache
cache:
  directories:
  - node_modules