language: node_js
node_js: lts/*
sudo: false

before_install:
- npm i -g greenkeeper-lockfile yarn
- &prepKey if [[ $GH_TOKEN ]]; then ./prepare-gpg-key.sh; fi;
- greenkeeper-lockfile-update

install: yarn install --check-files

script:
- yarn run tslint
- if [[ $GH_TOKEN ]]; then yarn run build && semantic-release --dry-run --branch $TRAVIS_BRANCH; else yarn run typecheck; fi;
- yarn run test --forbid-only --forbid-pending

after_success: cat ./coverage/lcov.info | coveralls

after_script: if [[ $GH_TOKEN ]]; then greenkeeper-lockfile-upload; fi;

cache:
  yarn: true

stages:
- Test
- Release

jobs:
  include:
  - stage: Test
  - stage: Release
    if: branch = master AND type = push AND (NOT tag IS present)
    before_install: &bfiRelease
    - npm i -g yarn
    - *prepKey
    before_script: &bfsRelease yarn run build
    script: semantic-release
    after_success: []
    after_script: []
  - stage: Release
    if: tag IS present
    before_install: *bfiRelease
    before_script: *bfsRelease
    script: yarn run tsdoc
    after_success: []
    after_script: []
    deploy:
      on:
        tags: true
      provider: pages
      local-dir: docs
      committer-from-gh: true
      skip_cleanup: true
      github-token: $GH_TOKEN
