language: node_js
node_js: lts/*
sudo: false

before_install:
- npm i -g greenkeeper-lockfile yarn
- &prepKey if [[ $GH_TOKEN ]]; then ./prepare-gpg-key.sh; fi;
- greenkeeper-lockfile-update

install: yarn install --check-files

script:
- yarn run tslint
- yarn run typecheck
- yarn run test --forbid-only --forbid-pending

after_success: cat ./coverage/lcov.info | coveralls

after_script: if [[ $GH_TOKEN ]]; then greenkeeper-lockfile-upload; fi;

before_cache: rm -rf ./node_modules/.cache
cache:
  yarn: true
  directories:
  - node_modules

stages:
- Test
- name: Release
  if: branch = master AND type = push

jobs:
  include:
  - stage: Test
  - stage: Release
    before_install:
    - npm i -g yarn
    - *prepKey
    before_script:
    - yarn run build
    - yarn run doctoc
    script: semantic-release
    after_success: []
    after_script: []
    before_deploy:
    - yarn run tsdoc
    deploy:
      provider: pages
      local-dir: docs
      committer-from-gh: true
      skip_cleanup: true
      github-token: $GH_TOKEN
      on:
        branch: master
